//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisKomputerowy_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SerwisKomputerowyEntities : DbContext
    {
        public SerwisKomputerowyEntities()
            : base("name=SerwisKomputerowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Urządzenia> Urządzenia { get; set; }
        public virtual DbSet<Usterki> Usterki { get; set; }
        public virtual DbSet<Zlecenia_dla_klienta> Zlecenia_dla_klienta { get; set; }
    }
}
