//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisKomputerowy_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenia_dla_klienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenia_dla_klienta()
        {
            this.Usterki = new HashSet<Usterki>();
        }
    
        public int idZlecenia { get; set; }
        public Nullable<System.DateTime> Data_przyjęcia_zlecenia { get; set; }
        public Nullable<System.DateTime> Data_wykonania { get; set; }
        public Nullable<decimal> Całkowity_koszt { get; set; }
        public int idKlienta_fk { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usterki> Usterki { get; set; }
    }
}
